bitesApp/bites/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views

''' ........... register bites views to rest_framework router ...........'''
router = routers.DefaultRouter()
router.register(r'categories', views.CategorieViewSet)
router.register(r'menus', views.MenuViewSet)

'''........ paths to bites views ......''' 

app_name = 'bites'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'), #... path to HomeView 
    path('new/', views.CreateBites.as_view(), name='new'), #... path to CreateBites view
    path('<int:pk>/', views.DetailView.as_view(), name='detail'), #... path to DetailView
    path('<pk>/update', views.UpdateBites.as_view(), name='update'), #... path to UpdateBites view
    path('<pk>/delete', views.DeleteBites.as_view(), name='delete'), #... path to DeleteBites 
   #........... path to rest_framework router ...........
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

bitesApp/bitesApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

''' path to bites && admin urls '''

urlpatterns = [
    path('bites/', include('bites.urls')),
    path('admin/', admin.site.urls)
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bitesApp/bites/models.py
from django.db import models
from django.urls import reverse


'''........ modal for storing bites categories ......''' 

class Categorie(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name

'''........ modal for storing bites  ......''' 

class Menu(models.Model):
    category = models.ForeignKey(Categorie, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.IntegerField()
    image = models.ImageField(max_length=255,upload_to='images', default='default.jpg')

    def get_absolute_url(self):
       return reverse('bites:detail',kwargs={'pk':self.pk})
    
    def __str__(self):
        return self.name

bitesApp/bites/views.py
from django.shortcuts import render
from .models import Menu, Categorie
from django.views import generic
from django.urls import reverse_lazy
from rest_framework import viewsets
from .serializers import MenuSerializer, CategorieSerializer


'''........ class based built-in view for listing modal objects ......''' 

class HomeView(generic.ListView):

    template_name = 'bites/home.html'
    context_object_name = 'bites_list'

    def get_queryset(self):

        return Menu.objects.filter()

'''........ class based built-in view for view modal object ......''' 

class DetailView(generic.DetailView):

    model = Menu
    template_name = 'bites/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

'''........ class based built-in view for create modal object ......''' 

class CreateBites(generic.CreateView):
    model = Menu
    template_name = 'bites/new.html'
    fields = ['name','price','category','image']
    

'''........ class based built-in view for update modal object ......'''    
    
class UpdateBites(generic.UpdateView):
    model = Menu
    template_name = 'bites/update.html'
    fields = ['name','price','category','image']

'''........ class based built-in view for delete modal object ......'''

class DeleteBites(generic.DeleteView):
    model = Menu
    template_name = 'bites/delete.html'
    success_url = reverse_lazy('bites:home')


""" display bites modals as json """

class MenuViewSet(viewsets.ModelViewSet):
    queryset = Menu.objects.all()
    serializer_class = MenuSerializer

class CategorieViewSet(viewsets.ModelViewSet):
    queryset = Categorie.objects.all()
    serializer_class = CategorieSerializer


    
    

bitesApp/bites/templates/bites/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Bites App{% endblock %}</title>
    <script src="https://kit.fontawesome.com/70c20a4914.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500;600;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'bites/css/app.css' %}">
</head>

<body>
    <div id="navbar">
        {% block navbar %}
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="navbar">
            <div class="container-fluid">
                <a class="navbar-brand" href="#"><span>U</span>~bites.co</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav mb-2 mb-lg-0  mx-auto" style="width: 10px;">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#section1">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#section2">Aboutus</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{%  url 'bites:home' %}">Bites</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{%  url 'bites:new' %}">New</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#section6">SignIn</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#section6">SignOut</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% endblock %}
    </div>

    <div id="main">
        {% block main %}{% endblock %}
    </div>

    <div id="footer">
        {% block footer %}
        <div class="container-fluid footer">
            <span>Developed by: Makyao Pro</span>
        </div>
        {% endblock %}
    </div>
<script src='https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js'></script>
</body>
</html>

bitesApp/bites/templates/bites/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>bites</title>
</head>
<body>
<h1>Delete Bite</h1>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ menu }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>
</body>
</html>

bitesApp/bites/templates/bites/detail.html
{% extends 'bites/base.html' %}

{% block title %}{{ menu.name }}{% endblock %}

{% block main %}
<div id="detail" class="container-fluid main">
    <h1> {{ menu.name }} </h1>
    <div class="row">
        <div class="col-md-6 p-5">
            <img src="{{ menu.image.url }}" class="img-fluid" alt='bites picture'>
        </div>
        <div class="col-md-6 p-5 mt-5 food">
            <h4 class="mb-2">price:  {{ menu.price }}$</h4>
            <h4>category:  {{ menu.category }}</h4>
            <div class="mt-3">
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span>
            </div>
            <div class="mt-5">
                <a href="{% url 'bites:update' menu.id %}"  class="btn btn1 btn-sm">Update Bite</a>
                <a href="{% url 'bites:delete' menu.id %}"  class="btn btn1 btn-sm" style='background-color:red'>Delete Bite</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

bitesApp/bites/templates/bites/home.html
{% extends "bites/base.html" %}

{% block title %}Home{% endblock %}

{% block main %}
       <div class="container-fluid main" >
        <h1>Available <span>Bites</span></h1>
        {%  if bites_list %}
        <div class="row foods">
            {% for bite in bites_list %}
            <div class="col-md-4 food">
                <div class="card mx-auto">
                    <img src="{{ bite.image.url }}" class="card-img-top img-fluid" alt="...">
                    <div class="card-body">

                        <div class="row">
                            <div class="col-sm-6">
                                <h6><b>{{ bite.name }}</b> </h6>
                            </div>
                            <div class="col-sm-6">
                                <a href="{% url 'bites:detail' bite.id %}" class="btn btn1 btn-sm">See More</a>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <span class="fa fa-star"></span>
                                <span class="fa fa-star"></span>
                                <span class="fa fa-star"></span>
                                <span class="fa fa-star"></span>
                                <span class="fa fa-star"></span>
                            </div>
                            <div class="col-sm-6 p-2">
                                <h6><b>{{ bite.price }}$</b> </h6>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    
{% endblock %}

bitesApp/bites/templates/bites/new.html
{% extends 'bites/base.html' %}
{% block title %}New{% endblock %}
{% block main %}
    <div class="container-fluid">
        <form method="post" enctype="multipart/form-data" class="main">{% csrf_token %}
            <h1>Add New Bites</h1>
            {% comment %} {{ form.as_p }} {% endcomment %}
            <div  class="mb-3">
                <label class="form-label">Enter Bite Name:</label>
                {{ form.name }}
            </div>
            <div  class="mb-3">
                <label class="form-label">Enter Bite Price:</label>
                {{ form.price }}
            </div>
            <div  class="mb-3">
                <label class="form-label">Enter Bite Category:</label>
                {{ form.category }}
            </div>
            <div  class="mb-3">
                <label class="form-label">Upload Image:</label>
                {{ form.image }}
            </div>
            <div  class="mb-3">
            <input type="submit" value="Save">
            </div>
          </form>
    </div>
{% endblock %}
{% block footer %}
<div class="container-fluid footer fixed-bottom">
    <span>Developed by: Makyao Pro</span>
</div>
{% endblock %}

bitesApp/bites/templates/bites/update.html
{% extends 'bites/base.html' %}

{% block title %}update{% endblock %}

{% block main %}
<div class="container-fluid main">
    <h1>Edit Bites</h1>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        {% comment %} {{ form.as_p }} {% endcomment %}
        <div  class="mb-3">
            <label class="form-label">Enter Bite Name:</label>
            {{ form.name }}
        </div>
        <div  class="mb-3">
            <label class="form-label">Enter Bite Price:</label>
            {{ form.price }}
        </div>
        <div  class="mb-3">
            <label class="form-label">Enter Bite Category:</label>
            {{ form.category }}
        </div>
        <div  class="mb-3">
            <label class="form-label">Upload Image:</label>
            {{ form.image }}
        </div>
        <div  class="mb-3">
        <input type="submit" value="Update">
        </div>
    </form>
    </div>
{% endblock %}
{% block footer %}
<div class="container-fluid footer fixed-bottom">
    <span>Developed by: Makyao Pro</span>
</div>
{% endblock %}